app/urls.py
from django.urls import path
from . import views  # O '.' significa 'importe da pasta atual'

urlpatterns = [
    # Quando alguém visitar a URL raiz deste app (ex: /), 
    # chame a função 'app_view' que está em 'views.py'.
    # O 'name' é um apelido opcional que usaremos mais tarde.
    path('', views.home_view, name='home'),
    path('metodologia/', views.metodologia_view, name='metodologia'),
    path('contato/', views.contato_view, name='contato'),
    path('assinaturas/', views.assinaturas_view, name='assinaturas'),
    path('curso/<int:pk>/',views.curso_detalhe_view, name = 'curso_detalhe'),
    path('curso/criar/',views.curso_form_view, name = 'curso_form'),
    path('curso/editar/<int:pk>/',views.editar_curso_view, name = 'curso_editar'),
    path('curso/deletar/<int:pk>/',views.deletar_curso_view, name = 'curso_deletar'),
    path('cadastro/', views.cadastro_view, name = 'cadastro'),
    



    
    # Se você tivesse outras páginas neste app, você as adicionaria aqui:
    # ex: path('sobre/', views.sobre_view, name='sobre'),
    # ex: path('contato/', views.contato_view, name='contato'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include  # 1. IMPORTANTE: Importe o 'include'

urlpatterns = [
    path('admin/', admin.site.urls),
    # 2. ESSA É A LINHA PRINCIPAL:
    # "Qualquer URL que comece com '' (a raiz do site),
    # inclua o arquivo 'urls.py' do nosso app 'app'."
    path('', include('app.urls')),
]
urlpatterns = [
 path('admin/', admin.site.urls),
 path('', include('app.urls')),
 path('accounts/', include('django.contrib.auth.urls')),
 # suas outras urls aqui
]

app/models.py
from django.db import models

class Curso(models.Model):
    # 'Back-end com Django', 'PowerBI', etc.
    nome = models.CharField(max_length=200) 
    
    # 'Gustavo'
    instrutor = models.CharField(max_length=100)
    
    # Armazenamos o NÚMERO (40), não o texto "40 horas".
    # O texto "horas" será colocado no template.
    carga_horaria = models.IntegerField()
    
    # 'Iniciante'
    # Usar 'choices' é uma boa prática para campos com valores fixos
    NIVEL_CHOICES = [
        ('Iniciante', 'Iniciante'),
        ('Intermediário', 'Intermediário'),
        ('Avançado', 'Avançado'),
    ]
    nivel = models.CharField(max_length=50, choices=NIVEL_CHOICES, default='Iniciante')
    descricao = models.CharField(max_length = 1000, default ='')

    def __str__(self):
        # Isso ajuda a ver o nome do curso no painel Admin
        return self.nome
    
class Plano(models.Model):
     nome = models.CharField(max_length=200) 
     preco = models.DecimalField(max_digits= 8, decimal_places=2)
     beneficios = models.CharField()
     destaque = models.BooleanField(default = False)

     def __str__(self):
            return f'{self.nome}- R${self.preco}'

    

app/forms.py
from django import forms
from .models import Curso
class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = '__all__' # Inclui todos os campos do Model
 # Alternativa: fields = ['nome', 'descricao', 'carga_horaria']

app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *  # 1. Importar
from .forms import CursoForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import Group # <-- Importação para cadastro usuario do grupo Cliente


def home_view(request):
    # 2. PEDIR AO BANCO:
    todos_os_cursos = Curso.objects.all()
    
    context = {
        'instrutor': 'Gustavo',
        'logado': request.user.is_authenticated,
        'cursos': todos_os_cursos  # 3. Passar dados reais
    }
    
    # 4. Chamar o template
    return render(request, 'home.html', context)

def metodologia_view(request):
    return render(request, 'metodologia.html')

def contato_view(request):
    return render(request, 'contato.html')

def assinaturas_view(request):
    todas_as_assinaturas=Plano.objects.all()

    context = {
        "planos" : todas_as_assinaturas
    }

    return render(request, 'assinaturas.html', context)

def curso_detalhe_view(request, pk):
    # Busca o curso com o ID específico
    curso = get_object_or_404(Curso, pk=pk)
    
    # Renderiza o template passando o curso
    return render(request, 'curso_detalhe.html', {'curso': curso})

def curso_form_view(request):
    if request.method == 'POST':
        # Usuário enviou dados preenchidos
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()  # Salva no banco de dados
            return redirect('home')  # Redireciona para a página inicial
    else:
        # Usuário quer ver o formulário vazio
        form = CursoForm()
    
    return render(request, 'curso_form.html', {'form': form})

# Use 'pk' em vez de 'id' para manter o padrão do urls.py (<int:pk>)
def editar_curso_view(request, pk):
    # 1. Busca o curso com segurança (se não achar, dá erro 404)
    curso = get_object_or_404(Curso, pk=pk)
 
    # 2. Preenche o formulário com os dados existentes (instance=curso)
    #    O "request.POST or None" é um atalho inteligente:
    #    Se tem dados (POST), usa eles. Se não tem (GET), usa None.
    form = CursoForm(request.POST or None, instance=curso)
 
    if form.is_valid():
        form.save()
        return redirect('home') # Redireciona para a lista (nome da sua rota home)
 
    # 3. CORREÇÃO: Renderiza o MESMO template de criação
    return render(request, 'curso_form.html', {'form': form})

def deletar_curso_view(request, pk):
    curso = get_object_or_404(Curso, pk=pk)
    
    if request.method == 'POST':
        # Só apaga se vier do form
        curso.delete()
        return redirect('home')
    
    # GET mostra confirmação
    return render(request,'confirmar_exclusao.html',{'curso': curso})

def cadastro_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            # --- LÓGICA DE GRUPO ---
            # Pega o grupo "Client". 
            # Nota: O grupo PRECISA existir no Admin antes de rodar isso.
            grupo_client = Group.objects.get(name='Client')
            user.groups.add(grupo_client)

            # Login automático
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    
    return render(request,'registration/cadastro.html',{'form': form})

app/templates/assinaturas.html
{% extends 'base.html' %}

{% block titulo %}Planos e Preços - DevSchool{% endblock %}

{% block conteudo %}
    
    <div class="container">
        <h1 class="text-center mb-30" style="color: var(--text-main);">Escolha seu Plano de Estudos</h1>
        
        <div class="plans-container">
            
            {% for plano in planos %}
                <div class="plan-card {% if plano.destaque %}highlight{% endif %}">
                    
                    {% if plano.destaque %}
                        <div class="badge-recommended">Recomendado</div>
                    {% endif %}

                    <h2 class="plan-name">{{ plano.nome }}</h2>
                    
                    <div class="plan-price">
                        R$ {{ plano.preco }}
                    </div>
                    
                    <div class="plan-benefits">
                        {{ plano.beneficios }}
                    </div>

                    <button class="btn-plan {% if plano.destaque %}btn-highlight{% else %}btn-outline{% endif %}">
                        Assinar {{ plano.nome }}
                    </button>

                </div>
            {% endfor %}

        </div>
    </div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DevSchool - Sua Escola de Programação</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header>
    <nav>
        <h2>🦅 DevSchool 😎</h2>
        
        <div>
            <a href="/">Cursos</a>
            <a href="/metodologia">Metodologia</a>
            <a href="/contato">Contato</a>
            <a href="/assinaturas">Nossos Planos</a>
            
            {% if user.is_authenticated %} <span style="margin-left: 15px; font-size: 0.9em; color: #bdc3c7;">
                    Bem vindo, {{ user.username }}
                </span>
            {% else %}
                <a href="{% url 'login'%} ">LOGIN</a>
            {% endif %}
        </div>
    </nav>
    </header>
    
    <main>
    <div class="container">
        {% block conteudo %}
        {% endblock %}
    </div>
    </main>
    
    <footer>© 2025 DevSchool - Ensinando o Futuro</footer>
</body>
</html>

app/templates/confirmar_exclusao.html
{% extends 'base.html' %}

{% block titulo %}Excluir Curso - DevSchool{% endblock %}

{% block conteudo %}
    {% if perms.app.delete_curso %}
    
    <div class="container delete-container">
        
        <div class="delete-card">
            
            <svg xmlns="http://www.w3.org/2000/svg" class="warning-icon-large" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
                <line x1="12" y1="9" x2="12" y2="13"></line>
                <line x1="12" y1="17" x2="12.01" y2="17"></line>
            </svg>

            <h1 class="delete-title">Tem certeza?</h1>
            
            <p class="delete-text">
                Você está prestes a excluir permanentemente o curso: <br>
                <strong style="color: var(--text-main); font-size: 1.2em;">"{{ curso.nome }}"</strong>.
                <br><br>
                <span style="color: var(--danger-color); font-size: 0.9em;">⚠️ Esta ação não pode ser desfeita.</span>
            </p>

            <form method="post">
                {% csrf_token %}
                
                <div class="delete-actions">
                    <a href="{% url 'curso_detalhe' curso.pk %}" class="btn btn-outline" style="text-decoration: none;">
                        Cancelar
                    </a>

                    <button type="submit" class="btn btn-danger">
                        Sim, Excluir Curso
                    </button>
                </div>
            </form>

        </div>
        {% else %}
        <h1 class="text-center mb-30" style="color: var(--text-main);">Você precisa ter permissão para acessar essa página</h1>

        {% endif %}

    </div> 

{% endblock %}

app/templates/contato.html
{% extends 'base.html' %}

{% block titulo %}Fale Conosco - DevSchool{% endblock %}

{% block conteudo %}
    
    <div class="form-wrapper">
        
        <h1 class="text-center mb-30">Fale Conosco</h1>
        
        <div class="alert-warning">
            <strong>⚠️ Atenção:</strong> Este formulário é apenas uma simulação visual (Front-end). <br>
            O envio de dados será implementado nas próximas aulas.
        </div>

        <form>
            
            <div class="form-group">
                <label for="id_nome">Nome:</label>
                <input type="text" id="id_nome" class="form-control" placeholder="Digite seu nome">
            </div>

            <div class="form-group">
                <label for="id_email">E-mail:</label>
                <input type="email" id="id_email" class="form-control" placeholder="seu@email.com">
            </div>

            <div class="form-group">
                <label for="id_mensagem">Mensagem:</label>
                <textarea id="id_mensagem" class="form-control" placeholder="Como podemos te ajudar?"></textarea>
            </div>
            
            <button type="button" class="btn btn-primary" onclick="alert('Formulário Simulado! Nada foi enviado.')">
                Enviar Mensagem
            </button>

        </form>
    </div>

{% endblock %}

app/templates/curso_detalhe.html
{% extends 'base.html' %}

{% block titulo %}{{ curso.nome }} - Detalhes{% endblock %}

{% block conteudo %}
  
  <div class="detail-wrapper">
    
    <div class="detail-card">
      
      <div class="detail-header">
        <span class="badge-level">{{ curso.nivel }}</span>
        <h1 class="detail-title">{{ curso.nome }}</h1>
      </div>

      <div class="detail-stats">
        <div class="stat-item">
            <label>Instrutor</label>
            <span>{{ curso.instrutor }}</span>
        </div>
        <div class="stat-item">
            <label>Carga Horária</label>
            <span>{{ curso.carga_horaria }} horas</span>
        </div>
        <div class="stat-item">
            <label>Certificado</label>
            <span>Sim, incluso</span>
        </div>
      </div>
      
      <div class="detail-description">
        <h3 style="color: var(--text-main); margin-bottom: 15px;">Sobre o Curso</h3>
        {{ curso.descricao|linebreaks }}
      </div>
      
      <div class="detail-actions" style="justify-content: space-between; align-items: center;">
        
        <div>
            <a href="/" class="btn btn-outline" style="text-decoration: none;">
                ← Voltar
            </a>
        </div>

        <div style="display: flex; gap: 10px;">
          {% if perms.app.change_curso %}
          
            
                <a href="{% url 'curso_editar' curso.pk %}" class="btn btn-primary" style="text-decoration: none; background-color: #f59e0b; color: #fff;">
                    Editar
                </a>
                {% endif %}

                {% if perms.app.change_curso %}

                <a href="{% url 'curso_deletar' curso.pk %}" class="btn btn-danger" style="text-decoration: none;">
                    Excluir
                </a>
                {% endif %}
            
        </div>

      </div>

    </div>

  </div>

{% endblock %}

app/templates/curso_form.html
{% extends 'base.html' %}

{% block titulo %}
    {% if form.instance.pk %}Editar{% else %}Novo{% endif %} Curso - DevSchool
{% endblock %}

{% block conteudo %}
    {% if perms.app.change_curso %}
    
    <div class="form-wrapper">
        
        <h1 class="text-center mb-30" style="color: var(--text-main);">
            {% if form.instance.pk %}
                Editar Curso
            {% else %}
                Cadastrar Novo Curso
            {% endif %}
        </h1>

        <form method="post">
            <!-- CSRF valida as informações de envio, garantindo a segurança da requisição-->
            {% csrf_token %}
            
            <div class="django-raw-form">
                <!-- form.as_p cria automaticamente o formulario nos conformes do modelo Curso -->
                {{ form.as_p }}
            </div>

            <div style="display: flex; gap: 10px; margin-top: 25px;">
                <button type="submit" class="btn btn-primary">
                    Salvar
                </button>
                
                <a href="/" class="btn btn-outline" style="text-decoration: none; text-align: center;">
                    Cancelar
                </a>
            </div>
        </form>

    </div>
    {% else %}
    <h1 class="text-center mb-30" style="color: var(--text-main);">Você precisa ter permissão para acessar essa página</h1>

    {% endif %}
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block titulo %}Cursos Disponíveis - DevSchool{% endblock %}

{% block conteudo %}

<div class="container">

    <div class="text-center mb-30">
        <h1 style="color: var(--text-main);">Cursos Disponíveis</h1>
        <p style="color: var(--text-secondary);">Explore nosso catálogo e comece a codar hoje.</p>
    </div>

    {% if perms.app.add_curso %}
    <div style="text-align: right; margin-bottom: 20px;">
        <a href="{% url 'curso_form' %}" class="btn btn-primary" style="display: inline-block; width: auto;">
            + Novo Curso
        </a>
    </div>
    {% endif %}

    <div class="courses-container">

        {% for curso in cursos %}
        <div class="course-card" style="position: relative;">

            {% if perms.app.change_curso %}
            <a href="{% url 'curso_editar' curso.pk %}" class="btn-edit-icon" title="Editar Curso">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                </svg>
            </a>
            {% endif %}


            <div class="course-header">
                <span class="badge-level">{{ curso.nivel }}</span>
                <h3 class="course-title">{{ curso.nome }}</h3>
            </div>

            <div class="course-info">
                <p><strong>Instrutor:</strong> {{ curso.instrutor }}</p>
                <p><strong>Carga:</strong> {{ curso.carga_horaria }} horas</p>
            </div>

            <a href="{% url 'curso_detalhe' curso.pk %}" class="btn-course">
                Ver Detalhes
            </a>

        </div>
        {% empty %}
        <p style="color: var(--text-secondary);">Nenhum curso disponível no momento.</p>
        {% endfor %}

    </div>
</div>

{% endblock %}

app/templates/metodologia.html
{% extends 'base.html' %}
{% block conteudo %}
<h1>Nossa Metodologia</h1>
<p>Na DevSchool, acreditamos em aprendizado prático.</p>
<p>Nossos cursos combinam teoria sólida com projetos reais, 
preparando você para o mercado de trabalho.</p><br><br>
<ul>
 <li>Aulas hands-on com instrutores experientes</li>
 <li>Projetos que vão para o seu portfólio</li>
 <li>Suporte contínuo da comunidade</li>
</ul>
{% endblock %}